

name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
         run:| 
              export FLASK_APP=app
              export FLASK_ENV=development
              flask run
