

name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: clones repo
      - uses: actions/checkout@v3
      - name: aws flask sample app
         run:| 
              export FLASK_APP=app
              export FLASK_ENV=development
              flask run
