name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: aws flask sample app
        run: |
             export FLASK_APP=app
             export FLASK_ENV=production
             npm i -g pm2
             pm2 restart "flask run"
