

name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: aws flask sample app
        run: |
             #sudo cat log.txt >> /var/log/flask.txt
             sudo fuser -k 5000/tcp
             export FLASK_APP=app
             export FLASK_ENV=development
             touch log.txt
             flask run >> log.txt 2>&1 &
        
